import Head from 'next/head';
import type { AppProps } from 'next/app';
import { SWRConfig } from 'swr';
import { Header } from 'components/common/Header/Header';
import { Footer } from 'components/common/Footer/Footer';
import { Content } from 'components/common/Content/Content';
import 'styles/reset.scss';
import 'styles/globals.css';


function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SWRConfig value={{fallback: pageProps.fallback}}>
      <>
        <Head>
          <title>Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Content >
          <Component {...pageProps} />
        </Content>
        <Footer />
      </>
    </SWRConfig>

  )
}

export default MyApp
